package com.itfaculty.progress.model;
// Generated Mar 15, 2017 7:37:19 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Labassistants generated by hbm2java
 */
@Entity
@Table(name="labassistants"
    ,catalog="nawalokahospital"
    , uniqueConstraints = @UniqueConstraint(columnNames="labassistant_username") 
)
public class Labassistants  implements java.io.Serializable {


     private Integer labassistantId;
     private String labassistantFirstname;
     private String labassistantLastname;
     private String labassistantUsername;
     private String labassistantPassword;
     private String labassistantType;
     private Date labassistantStime;
     private Date labassistantEtime;
     private Set<Records> recordses = new HashSet<Records>(0);

    public Labassistants() {
    }

	
    public Labassistants(String labassistantFirstname, String labassistantLastname, String labassistantUsername, String labassistantPassword, String labassistantType, Date labassistantStime, Date labassistantEtime) {
        this.labassistantFirstname = labassistantFirstname;
        this.labassistantLastname = labassistantLastname;
        this.labassistantUsername = labassistantUsername;
        this.labassistantPassword = labassistantPassword;
        this.labassistantType = labassistantType;
        this.labassistantStime = labassistantStime;
        this.labassistantEtime = labassistantEtime;
    }
    public Labassistants(String labassistantFirstname, String labassistantLastname, String labassistantUsername, String labassistantPassword, String labassistantType, Date labassistantStime, Date labassistantEtime, Set<Records> recordses) {
       this.labassistantFirstname = labassistantFirstname;
       this.labassistantLastname = labassistantLastname;
       this.labassistantUsername = labassistantUsername;
       this.labassistantPassword = labassistantPassword;
       this.labassistantType = labassistantType;
       this.labassistantStime = labassistantStime;
       this.labassistantEtime = labassistantEtime;
       this.recordses = recordses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="labassistant_id", unique=true, nullable=false)
    public Integer getLabassistantId() {
        return this.labassistantId;
    }
    
    public void setLabassistantId(Integer labassistantId) {
        this.labassistantId = labassistantId;
    }

    
    @Column(name="labassistant_firstname", nullable=false, length=100)
    public String getLabassistantFirstname() {
        return this.labassistantFirstname;
    }
    
    public void setLabassistantFirstname(String labassistantFirstname) {
        this.labassistantFirstname = labassistantFirstname;
    }

    
    @Column(name="labassistant_lastname", nullable=false, length=100)
    public String getLabassistantLastname() {
        return this.labassistantLastname;
    }
    
    public void setLabassistantLastname(String labassistantLastname) {
        this.labassistantLastname = labassistantLastname;
    }

    
    @Column(name="labassistant_username", unique=true, nullable=false, length=100)
    public String getLabassistantUsername() {
        return this.labassistantUsername;
    }
    
    public void setLabassistantUsername(String labassistantUsername) {
        this.labassistantUsername = labassistantUsername;
    }

    
    @Column(name="labassistant_password", nullable=false)
    public String getLabassistantPassword() {
        return this.labassistantPassword;
    }
    
    public void setLabassistantPassword(String labassistantPassword) {
        this.labassistantPassword = labassistantPassword;
    }

    
    @Column(name="labassistant_type", nullable=false, length=100)
    public String getLabassistantType() {
        return this.labassistantType;
    }
    
    public void setLabassistantType(String labassistantType) {
        this.labassistantType = labassistantType;
    }

    @Temporal(TemporalType.TIME)
    @Column(name="labassistant_stime", nullable=false, length=8)
    public Date getLabassistantStime() {
        return this.labassistantStime;
    }
    
    public void setLabassistantStime(Date labassistantStime) {
        this.labassistantStime = labassistantStime;
    }

    @Temporal(TemporalType.TIME)
    @Column(name="labassistant_etime", nullable=false, length=8)
    public Date getLabassistantEtime() {
        return this.labassistantEtime;
    }
    
    public void setLabassistantEtime(Date labassistantEtime) {
        this.labassistantEtime = labassistantEtime;
    }

//@OneToMany(fetch=FetchType.LAZY, mappedBy="labassistants")
//    public Set<Records> getRecordses() {
//        return this.recordses;
//    }
//    
//    public void setRecordses(Set<Records> recordses) {
//        this.recordses = recordses;
//    }




}


